apiVersion: v1
kind: Secret
metadata:
  name: pathsense-secrets
type: Opaque
data:
  openweathermap-api-key: {{ .Values.secrets.openweathermapApiKey | b64enc | quote }}
  twilio-account-sid: {{ .Values.secrets.twilioAccountSid | b64enc | quote }}
  twilio-auth-token: {{ .Values.secrets.twilioAuthToken | b64enc | quote }}
  twilio-from-number: {{ .Values.secrets.twilioFromNumber | b64enc | quote }}
  postgres-password: {{ .Values.secrets.postgresPassword | b64enc | quote }}
  redis-password: {{ .Values.secrets.redisPassword | b64enc | quote }}
